### ISSUE TITLE
Tests no longer compile with hakyll 4.15

### ISSUE THREAD

**Issue by sternenseemann** [LaurentRDC/hakyll-images#10]
```
Building test suite 'spec' for hakyll-images-1.1.0..
[ 1 of 11] Compiling Hakyll.Images.Common ( library/Hakyll/Images/Common.hs, dist/build/spec/spec-tmp/Hakyll/Images/Common.o )
[ 2 of 11] Compiling Hakyll.Images.CompressJpg ( library/Hakyll/Images/CompressJpg.hs, dist/build/spec/spec-tmp/Hakyll/Images/CompressJpg.o )
[ 3 of 11] Compiling Hakyll.Images.CompressJpg.Tests ( tests/Hakyll/Images/CompressJpg/Tests.hs, dist/build/spec/spec-tmp/Hakyll/Images/CompressJpg/Tests.o )
[ 4 of 11] Compiling Hakyll.Images.Metadata ( library/Hakyll/Images/Metadata.hs, dist/build/spec/spec-tmp/Hakyll/Images/Metadata.o )
[ 5 of 11] Compiling Hakyll.Images.Resize ( library/Hakyll/Images/Resize.hs, dist/build/spec/spec-tmp/Hakyll/Images/Resize.o )
[ 6 of 11] Compiling Hakyll.Images    ( library/Hakyll/Images.hs, dist/build/spec/spec-tmp/Hakyll/Images.o )
[ 7 of 11] Compiling Hakyll.Images.Metadata.Tests ( tests/Hakyll/Images/Metadata/Tests.hs, dist/build/spec/spec-tmp/Hakyll/Images/Metadata/Tests.o )
[ 8 of 11] Compiling Hakyll.Images.Common.Tests ( tests/Hakyll/Images/Common/Tests.hs, dist/build/spec/spec-tmp/Hakyll/Images/Common/Tests.o )

tests/Hakyll/Images/Common/Tests.hs:50:8: error:
    • Couldn't match expected type ‘IO a1’
                  with actual type ‘Rules a0
                                    -> IO
                                         (GHC.IO.Exception.ExitCode,
                                          Hakyll.Core.Rules.Internal.RuleSet)’
    • In a stmt of a 'do' block:
        _ <- run testConfiguration logger
               $ do match "*.jpg"
                      $ do route idRoute
                           compile $ loadImage >>= compressJpgCompiler 50
      In the expression:
        do logger <- L.new L.Error
           _ <- run testConfiguration logger $ do match "*.jpg" $ do ...
           _ <- assertBool "Image was not written"
                  <$>
                    (doesFileExist
                       $ destinationDirectory testConfiguration </> "piccolo.jpg")
           cleanTestEnv
      In an equation for ‘case1’:
          case1
            = do logger <- L.new L.Error
                 _ <- run testConfiguration logger $ do match "*.jpg" $ ...
                 _ <- assertBool "Image was not written"
                        <$>
                          (doesFileExist
                             $ destinationDirectory testConfiguration </> "piccolo.jpg")
                 ....
   |
4m50 |   _ <- run testConfiguration logger $ do
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

tests/Hakyll/Images/Common/Tests.hs:50:12: error:
    • Couldn't match expected type ‘RunMode’
                  with actual type ‘Configuration’
    • In the first argument of ‘run’, namely ‘testConfiguration’
      In the expression: run testConfiguration logger
      In a stmt of a 'do' block:
        _ <- run testConfiguration logger
               $ do match "*.jpg"
                      $ do route idRoute
                           compile $ loadImage >>= compressJpgCompiler 50
   |
50 |   _ <- run testConfiguration logger $ do
   |            ^^^^^^^^^^^^^^^^^

tests/Hakyll/Images/Common/Tests.hs:50:30: error:
    • Couldn't match expected type ‘Configuration’
                  with actual type ‘L.Logger’
    • In the second argument of ‘run’, namely ‘logger’
      In the expression: run testConfiguration logger
      In a stmt of a 'do' block:
        _ <- run testConfiguration logger
               $ do match "*.jpg"
                      $ do route idRoute
                           compile $ loadImage >>= compressJpgCompiler 50
   |
50 |   _ <- run testConfiguration logger $ do
   |                              ^^^^^^

tests/Hakyll/Images/Common/Tests.hs:51:5: error:
    • Couldn't match expected type ‘L.Logger’
                  with actual type ‘Rules ()’
    • In a stmt of a 'do' block:
        match "*.jpg"
          $ do route idRoute
               compile $ loadImage >>= compressJpgCompiler 50
      In the second argument of ‘($)’, namely
        ‘do match "*.jpg"
              $ do route idRoute
                   compile $ loadImage >>= compressJpgCompiler 50’
      In a stmt of a 'do' block:
        _ <- run testConfiguration logger
               $ do match "*.jpg"
                      $ do route idRoute
                           compile $ loadImage >>= compressJpgCompiler 50
   |
4m51 |     match "*.jpg" $ do
   |     ^^^^^^^^^^^^^^^^^^^...
[ 9 of 11] Compiling Hakyll.Images.Resize.Tests ( tests/Hakyll/Images/Resize/Tests.hs, dist/build/spec/spec-tmp/Hakyll/Images/Resize/Tests.o )
[11 of 11] Compiling Paths_hakyll_images ( dist/build/spec/autogen/Paths_hakyll_images.hs, dist/build/spec/spec-tmp/Paths_hakyll_images.o )
```

**Comment by LaurentRDC** [comment]
Thank you for your report, I will take a look tonight

**Comment by LaurentRDC** [comment]
This *should* be fixed in 48352aa. Can you please try again and let me know?

**Comment by sternenseemann** [comment]
Can confirm, new release would be neat.

**Comment by LaurentRDC** [comment]
Ask and you shall receive: [v1.1.1](https://hackage.haskell.org/package/hakyll-images-1.1.1)
