### ISSUE TITLE
Tests no longer compile with hakyll-4.16.8.0

### ISSUE THREAD

**Issue by sternenseemann** [LaurentRDC/hakyll-images#14]
```
Preprocessing test suite 'spec' for hakyll-images-1.3.0...
Building test suite 'spec' for hakyll-images-1.3.0...
[1 of 6] Compiling Hakyll.Images.Common.Tests ( tests/Hakyll/Images/Common/Tests.hs, dist/build/spec/spec-tmp/Hakyll/Images/Common/Tests.o )
[2 of 6] Compiling Hakyll.Images.Metadata.Tests ( tests/Hakyll/Images/Metadata/Tests.hs, dist/build/spec/spec-tmp/Hakyll/Images/Metadata/Tests.o )
[3 of 6] Compiling Hakyll.Images.Tests.Utils ( tests/Hakyll/Images/Tests/Utils.hs, dist/build/spec/spec-tmp/Hakyll/Images/Tests/Utils.o )
tests/Hakyll/Images/Tests/Utils.hs:34:32: error: [GHC-83865]
    • Couldn't match expected type ‘Provider’
                  with actual type ‘(Provider, [Identifier])’
    • In the ‘compilerProvider’ field of a record
      In the expression:
        CompilerRead
          {compilerConfig = testConfiguration,
           compilerUnderlying = underlying, compilerProvider = provider,
           compilerUniverse = S.empty, compilerRoutes = mempty,
           compilerStore = store, compilerLogger = logger}
      In an equation for ‘read'’:
          read'
            = CompilerRead
                {compilerConfig = testConfiguration,
                 compilerUnderlying = underlying, compilerProvider = provider,
                 compilerUniverse = S.empty, compilerRoutes = mempty,
                 compilerStore = store, compilerLogger = logger}
   |
34 |             compilerProvider = provider,
   |                                ^^^^^^^^
```

**Comment by LaurentRDC** [comment]
I'm taking a look now

**Comment by LaurentRDC** [comment]
Indeed this is because of https://github.com/jaspervdj/hakyll/pull/1084. When I approved that PR, I didn't think `newProvider` was external-facing.

I'll patch it right away

**Comment by LaurentRDC** [comment]
For what it's worth, I have release `hakyll` 4.17.0.0 which properly encodes the fact that there was a breaking change

**Comment by LaurentRDC** [comment]
Once you're ready to upgrade to `hakyll-4.17` (which only has a small breaking change), you can use the newly-released [`hakyll-images-1.3.1`](https://hackage.haskell.org/package/hakyll-images-1.3.1)
